@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 01 09:48:08 +0530 2023
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim NanoProcessorSimulation_func_impl -key {Post-Implementation:sim_1:Functional:NanoProcessorSimulation} -tclbatch NanoProcessorSimulation.tcl -view C:/Users/Deshitha/VivadoProjects/Nanoprocessor/NanoProcessorSimulation_behav.wcfg -view C:/Users/Deshitha/VivadoProjects/NanoProcessor_ExtraUpgraded/NanoProcessorSimulation_func_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
