# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.cache/wt [current_project]
set_property parent.project_path C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/2Way4BitMux/2Way4BitMux.srcs/sources_1/new/2Way4BitMux.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/8Way4BitMux/8Way4BitMux.srcs/sources_1/new/8Way4BitMux.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/AddSubUnit/AddSubUnit.srcs/sources_1/imports/new/AddSubUnit.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/Adder3Bit/Adder3Bit.srcs/sources_1/new/Adder3Bit.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/8Way4BitMux/8Way4BitMux.srcs/sources_1/imports/new/Decoder_2_to_4.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/8Way4BitMux/8Way4BitMux.srcs/sources_1/imports/new/Decoder_3_to_8.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/AddSubUnit/AddSubUnit.srcs/sources_1/imports/new/FA.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/AddSubUnit/AddSubUnit.srcs/sources_1/imports/new/HA.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/InstructionDecoder/InstructionDecoder.srcs/sources_1/new/InstructionDecoder.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/new/LUT_16_7.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/Mux2Way3Bit/Mux2Way3Bit.srcs/sources_1/new/Mux2Way3Bit.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/sources_1/imports/VivadoProjects/Mux8Way12Bit/Mux8Way12Bit.srcs/sources_1/new/Mux8Way12Bit.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/8Way4BitMux/8Way4BitMux.srcs/sources_1/imports/new/Mux_8_to_1.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/ProgramCounter/ProgramCounter.srcs/sources_1/new/ProgramCounter.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/sources_1/new/RAM.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/RegisterBank/RegisterBank.srcs/sources_1/imports/new/Reg.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/new/RegRam.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/VivadoProjects/RegisterBank/RegisterBank.srcs/sources_1/new/RegisterBank.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/imports/new/Slow_Clk.vhd
  C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/sources_1/new/NanoProcessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/constrs_1/imports/VivadoProjects/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/Deshitha/VivadoProjects/NanoProcessor_Upgrade7SubNot/NanoProcessor_Upgrade7SubNot.srcs/constrs_1/imports/VivadoProjects/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
